spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/contestant
    username: melissasantos
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
