package com.example.bachelorapi.model;

import jakarta.persistence.Entity;

import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

@Entity
public class Contestant {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //declaring what the contestant will consist of
    private Long id;
    private String name;
    private int age;
    private String occupation;
    private String season;
    private String location;

    //constructors + getters + setters

    public Contestant(){}
    //note: since we are using JPA entities, the id fiels is usually autogenerated by the database
    //hint when using import jakarta.persistence.GeneratedValue;
    public Contestant(String name, int age, String occupation, String season, String location) {
        this.name = name;
        this.age = age;
        this.occupation = occupation;
        this.season = season;
        this.location = location;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public int getAge() {
        return age;
    }
    public void setAge(int age) {
        this.age = age;
    }
    public String getOccupation() {
        return occupation;
    }
    public void setOccupation(String occupation) {
        occupation = occupation;
    }
    public String getSeason() {
        return season;
    }
    public void setSeason(String season) {
        this.season = season;
    }
    public String getLocation() {
        return location;
    }
    public void setLocation(String location) {
        this.location = location;
    }
}
